### ISSUE TITLE
step 2: otp failed to build, apk not found

### ISSUE THREAD

**Issue by iesemlr** [stadtnavi/stadtnavi-tutorial#12]
Hello,

We’re trying to set up the instances as described by the tutorial and met some issue. We arrived to finish step 1 and the instance of stadtnavi is running on port 8080.

For step 2 we got your data and modified it, so it takes data from Rhineland-Palatinate as well as the configuration from step 1. Unfortunately, we there have a problem. After executing the command

`docker-compose --env-file=.env.mobi4 up --build -d`

we receive the following error message

` => ERROR [ 2/10] RUN apk add --update zip &&     rm -rf /var/cache/apk/*                                                                0.6s `
` > [ 2/10] RUN apk add --update zip &&     rm -rf /var/cache/apk/*:
#5 0.527 /bin/sh: 1: apk: not found`
`executor failed running [/bin/sh -c apk add --update zip &&     rm -rf /var/cache/apk/*]: exit code: 127
ERROR: Service 'opentripplanner' failed to build : Build failed`

Is there something missing in the package? Can you help us understand, why this error occurs?

System: Windows 10
Docker (Desktop) version: 20.10.7
docker compose version: 1.29.2

Thank you in advance.

**Comment by leonardehrenfried** [comment]
Ah, this is because we switched the base image from alpine to debian.

I have just pushed an fix. Can you pull the latest version and try again?

**Comment by iesemlr** [comment]
Now it works. Thank you!
