### ISSUE TITLE
stadtnavi and OTP not communicating?

### ISSUE THREAD

**Issue by iesemlr** [stadtnavi/stadtnavi-tutorial#13]
Hello,

I have an issue with stadtnavi and OTP (locally). I got GTFS data into OTP and it works well.
Unfortunately, I can't see any GTFS data in stadtnavi as if both are not communicating. stadtnavi is empty.
Graphql API is set "true" (as suggested in Issue #11).

I'm not sure, what to do next and am looking forward to your reply.
Thank you in advance!

**Comment by iesemlr** [comment]
Hello again,

Is there any documentation describing how stadtnavi and otp are connected and in which way they work together?
If you could provide me the link to this documentation, if there is one, I would be very glad.

Thank you.

**Comment by leonardehrenfried** [comment]
Hi there,

it's a bit hard to figure out where your problem is. Can you post screenshots of your web inspector so I can see HTTP traffic.

Also, you can try just open the debug client on localhost:8080 and do a few queries there?

**Comment by leonardehrenfried** [comment]
Also, if you're on Matrix you can join the following room: https://matrix.to/#/#okfde-digitransit:matrix.org

There you can post your problem and myself and others can help.

**Comment by iesemlr** [comment]
Hello,

Thank you for replying. Web inspector looks like this on localhost:8080. It's taking the standard API set in the config file.

`const API_URL = process.env.API_URL || 'https://api.stadtnavi.de';`

Is this what you were asking for?


![image](https://user-images.githubusercontent.com/101876403/171407005-118ef132-a3b2-40d8-804a-516f45c0c996.png)

**Comment by leonardehrenfried** [comment]
Looks like the communication with the API endpoint is successful. Which area are you searching in? Are you aware that the stadtnavi backend only covers parts of Baden-Württemberg?

I think it might be quicker if we hop on a video call as I can't figure out what you're trying to do. If you want to do that email me. My address in in my profile.
